### ISSUE TITLE
Reproduce ifind with pytsk3

### ISSUE THREAD

**Issue by d-fence** [py4n6/pytsk#11]
I try to reproduce the "ifind" tool inside a python script. For example, we find an interesting string at some offset in an NTFS partition. I can calculate the cluster number find the inode number by passing this cluster number to the ifind utility.
I did not manage to reproduce that with pytsk3.
Is it possible already ?

**Comment by scudette** [comment]
Hi d-fence,
   The way to answer this question is to build a lookup table of all the known files and their allocation blocks and then search the lookup table for a file which might contain this block. You can either build the map in memory, or a better option is to build it into a database of some sort (e.g. sqlite) because that would take some time to pre-calculate. Then you lookup the block and see if it appears inside any file. If not it may be in unallocated area.

If you decide to do it in memory, a nice module to do this is intervaltree which you can just pip install: 
https://pypi.python.org/pypi/intervaltree/2.0.4

The second part of the problem is to iterate over all files and collect their runs. You can check out the code in the examples/istat.py example for this:
```
f = fs.open_meta(inode = inode)
t = IntervalTree()

for attr in f:
    for run in attr:
        t[run.addr:run.addr + run.len] = inode
```

Or something similar using sqlite.

If you do end up writing some code we would appreciate a contribution to the examples directory. 

Thanks,
Michael.

**Comment by d-fence** [comment]
Hi scudette,

thanks for your reply. I ended up using subprocess.Popen to launch ifind and and ffind, only using python to calculate the cluster for a given offset. I tought that there would be a python binding for the ifind tool.

**Comment by d-fence** [comment]
I think that this question can be closed.

**Comment by scudette** [comment]
pytsk is not a binding for the sleuthkit tools - it is a binding for the tsk library. The ifind tool is built atop the libtsk library and so it is out of scope for pytsk bindings. We can easily replicate the algorithm using pytsk as mentioned above but this might not be worth it depending on what you want to do.
