### ISSUE TITLE
Unable to access filename information from open_meta()

### ISSUE THREAD

**Issue by jahrome** [py4n6/pytsk#5]
Hi ! Don't know if it is a bug or me doing things wrong but I am unable to get the filename with open_meta():

$ fls -r /dev/nbd10p1
...
r/r 41-128-1:	testjer.txt
...

In [95]: %cpaste
Pasting code; enter '--' alone on the line to stop or use Ctrl-D.
:pytsk3.Img_Info('/dev/nbd10p1')
:img = pytsk3.Img_Info('/dev/nbd10p1')
:fs = pytsk3.FS_Info(img)
:f = fs.open_meta(41)
:print f.info.name
:m = f.next()
:m = f.next()
:print m.info.type
:print m.info.name
:<EOF>
None
TSK_FS_ATTR_TYPE_NTFS_FNAME
None

**Comment by joachimmetz** [comment]
I think this answers your question:
https://github.com/py4n6/pytsk/wiki/Development#getting-a-file-entry

**Comment by jahrome** [comment]
Thank you Joachim, I was suspecting this reason given open_dir provides
access to the filename... But correct me if I'm wrong, the filename is
also present in $FILE_NAME attributes in the MFT entry which could
provide the filename instead of having to search the directory tree ?
I want to implement "ifind -d" like functionnality to locate which file
contains a particular string in an image so I need to access the file
name information. Do you have any hint how I can achieve that ?

**Comment by joachimmetz** [comment]
> But correct me if I'm wrong, the filename is
> also present in $FILE_NAME attributes in the MFT entry which could
> provide the filename instead of having to search the directory tree ?

Yes, however there can be multiple $FILE_NAME attributes (e.g. hard links) how do you determine which one should be used solely on the MFT entry index?

You could try to iterate the attributes in [this way](https://github.com/py4n6/pytsk/wiki/Development#accessing-a-alternate-data-stream-ntfs) and print all the attributes instead of a single filename

You'll likely have to dig a bit in the SleuthKit API and how that maps to pytsk. Since pytsk is a thin Python wrapper around SleuthKit, it should be fairly close to its API.

**Comment by jahrome** [comment]
Thanks a lot, it works !

FTR:
f = fs.open_meta(inum)
for attr in f:
    if attr.info.type == pytsk3.TSK_FS_ATTR_TYPE_NTFS_FNAME:
    fn = f.read_random(66, attr.info.size, attr.info.type, attr.info.id)
